spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todo_db
    username: todo_user
    password: strong_password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
